version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Running build...
      - npm run build
  post_build:
    commands:
      - echo Build complete. Copying files to S3...
      - aws s3 sync build/ s3://ado-tabportal --delete

artifacts:
  files:
    - '**/*'
